<a href="https://colab.research.google.com/github/Omolabak5/data-and-python/blob/main/Copy_of_D_05a_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Numpy

---


## Creating new Numpy Arrays

As shown in the presentation, it is convention to import the whole numpy library using an alias:

`import numpy as np`

Every time you want to use a function from the numpy library you use the syntax:  

`np.function_name()`  

Create a new numpy array from a Python list of numbers
   
`arr = np.array([1,2,3])`

Or a new numpy matrix from a Python 2 dimensional list of numbers

`matrix = np.array([[1,2,3],[4,5,6]])`

Create a numpy array from a dataframe column (series):

`arr = df['column name'].to_numpy(datatype)`

where the datatype matches the data type of the column.



### Exercise 1 - create a new numpy array to hold the numbers from 1 to 10
---

Write a function called `make_array()` which will:
*   create a list of the numbers 1 to 10     -   *hint: try using range() if you are more confident working with lists*
*   create a new numpy array called **new_array** from that list
*   print `new_array`

Expected output:  
`[1 2 3 4 5 6 7 8 9 10] `



In [3]:
import numpy as np

def make_array():
  # add your code below here
  #using range , create a list of from 1 to 10
  num_list = [i for i in range (1,11)]

#create a new numpy array from the num_list above
  new_array = np.array([num_list])
  print(new_array)








# run and test the function against the expected output
make_array()

[[ 1  2  3  4  5  6  7  8  9 10]]


## Setting the number type in memory

As a reminder, set the memory type as follows, where **int8** is the datetype you wish to use.

`new_array = np.array([1, 2, 3], np.int8)`    


---
### Exercise 2 - create list of smallish numbers

Write a function which will:
*   assign the list `[31112, 32321, 24567, 456, 324, 789]` to a variable called **num_list** (which has been done for you already)   
*   create a new numpy array called **new_array** from `num_list`, with data size `int16`
*   print `new_array`  


Expected output:   
```
[31112 32321 24567 456 324 789]
```

*As an extra challenge, if you've complete the worksheet on user defined functions, change the function to accept num_list as a parameter, then the function should return the numpy array rather than print it.*

In [4]:
import numpy as np

def create_new_array():

  num_list = [31112, 32321, 24567, 456, 324, 789]
  #create a new array with data size int16
  new_array = np.array([num_list], np.int16)
  #print the new_array
  print(new_array)

  # add your code below here to turn num_list into a numpy array



# run and test the code against the expected output
create_new_array()

[[31112 32321 24567   456   324   789]]


---
### Exercise 3 - create a numpy array from a pandas dataframe column

Write a function which  will create a numpy array from the Fare column of the titanic dataset.

*Recap*:  *the Fare column is df['Fare'] (assuming your dataframe is called df)*

*  create a dataframe from the data set in the file at this url:  https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv (this has been done for you)
*  create a new numpy array called **fare** from the `Fare` column (*remember to specify the data type e.g. np.int32, float64 when using* `df.to_numpy()` *and consider what the datatype might be from looking at the expected output below*)  
*  print the `fare` array

Expected output:  
```
array([  7.25  ,  71.2833,   7.925 , ......  23.45  ,  30.    ,   7.75  ])
```

  

In [6]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv"
df = pd.read_csv(url)

def create_fare_series():
  # create a numpy array from the Fare column and print it
  fare = df['Fare'].to_numpy(np.float64)
  print(fare)



# run the function and test against the expected output.
create_fare_series()

[  7.25    71.2833   7.925   53.1      8.05     8.4583  51.8625  21.075
  11.1333  30.0708  16.7     26.55     8.05    31.275    7.8542  16.
  29.125   13.      18.       7.225   26.      13.       8.0292  35.5
  21.075   31.3875   7.225  263.       7.8792   7.8958  27.7208 146.5208
   7.75    10.5     82.1708  52.       7.2292   8.05    18.      11.2417
   9.475   21.       7.8958  41.5792   7.8792   8.05    15.5      7.75
  21.6792  17.8     39.6875   7.8     76.7292  26.      61.9792  35.5
  10.5      7.2292  27.75    46.9      7.2292  80.      83.475   27.9
  27.7208  15.2458  10.5      8.1583   7.925    8.6625  10.5     46.9
  73.5     14.4542  56.4958   7.65     7.8958   8.05    29.      12.475
   9.       9.5      7.7875  47.1     10.5     15.85    34.375    8.05
 263.       8.05     8.05     7.8542  61.175   20.575    7.25     8.05
  34.6542  63.3583  23.      26.       7.8958   7.8958  77.2875   8.6542
   7.925    7.8958   7.65     7.775    7.8958  24.15    52.      14.4542
  

---
### Exercise 4 - print first 5 and last 5 items in numpy array

Write a function which will create the same array as in the previous exercise (created from the Fare column in the titanic dataset):

*  print the first 5 items in the array (one per line)
*  print 5 lines of three dots (ie ...)
*  print the last 5 items in the array (one per line)

*Hint: You can slice an array from the beggining or the end and then print the values from that slice.*

Note: If you have run the cell above in this session, the dataframe **df** will still be available for you to use.

**Expected output**:  
7.25 <br>
71.2833 <br>
7.925 <br>
53.1 <br>
8.05  
...  
...  
...  
...  
...  
13.0 <br>
30.0 <br>
23.45 <br>
30.0 <br>
7.75



In [4]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv"
df = pd.read_csv(url)

def show_head_tail():
  # add your code below here to create a numpy array from the Fare column and print the head and tail, with dots as separators

  #get the colunm "Fare" from the dataframe column
  fare_arr = df['Fare'].to_numpy(np.float64)

  #get the first five items from fare
  for fare in fare_arr[:5]:
    print(fare)

  #Loop 5 times for dots separators
  for _ in range(5):
    print("...")  # Print three dots on each line

  #get the last five items from fare
  for fare in fare_arr[-5:]:
    print(fare)





# run the function and test against the expected output.
show_head_tail()

7.25
71.2833
7.925
53.1
8.05
...
...
...
...
...
13.0
30.0
23.45
30.0
7.75


---
### Exercise 5 - increase whole array by 20

Write a function which will:
*  create a numpy array of 12 numbers
*  create a new array adding 20 to each of the items in the first array  
*  print the new array

Test input:  
`[1,2,3,4,5,6,7,8,1,2,3,4]`

Expected output:  
`[21 22 23 24 25 26 27 28 21 22 23 24]`

In [5]:
import numpy as np

def increase_array():
  # add your code below to increase all values in an array by 20 and then to call the function

  #create numpy array of 12 numbers
  nums = np.array([1,2,3,4,5,6,7,8,1,2,3,4])

  #add 20 to each of the items in nums and print the new_array
  new_array = nums + 20
  print(new_array)




# run the function and test against the expected output.
increase_array()

[21 22 23 24 25 26 27 28 21 22 23 24]



---
### Exercise 6 - convert Titanic fares into 21st century values

Write a function which will:    
*  create a numpy array from the Fare column of the Titanic dataframe `df`
*  convert the fares into current value (multiply by a factor of 120.7045 - source https://www.in2013dollars.com/uk/inflation/1912?amount=32 *accessed 22/1/2022*)
*  sort the converted fares
*  print the first (the smallest) and last (greatest) values of the sorted fares.

Expected output:  
```
0.0
61840.4399214

```




In [7]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv"
df = pd.read_csv(url)

def get_current_fares():
  # add your code below to get the fares data into a numpy array, convert to today's prices and print stats

   #get the colunm "Fare" from the dataframe column
  fare_arr = df['Fare'].to_numpy(np.float64)
  converted_fares = fare_arr * 120.7045 #convert by multiplying all the items in "fare_arr" with current values

  #sort the converted_fares array by creating a new array
  sorted_converted_fares = np.sort(converted_fares)

  #print the minimum and maximum values of sorted fares
  print(min(sorted_converted_fares))
  print(max(sorted_converted_fares))





# run the function and test against expected output
get_current_fares()

0.0
61840.4399214


### Exercise 7 - filtering an array

Write a function that will take a numpy array of 20 random numbers between 1 and 10 use array filtering to print the following:
* numbers equal to 5 (arr == 5)
* numbers less than or equal to 5 (arr <= 5)
* numbers greater than 5 (arr > 5)
* numbers not equal to 5 (arr != 5)

Expected output:

`[5 5]` <br>
`[4 5 2 1 3 1 2 4 5 3 3 1]` <br>
`[9 8 8 7 6 7 8 9]` <br>
`[4 2 9 1 8 3 1 8 2 7 4 3 6 7 3 1 8 9]`


In [9]:
import numpy as np

def filter_an_array():
  arr = np.array([4, 5, 2, 9, 1, 8, 3, 1, 8, 2, 7, 4, 5, 3, 6, 7, 3, 1, 8, 9])
  # add your code below to filter the array above

  #create filters by broadcasting conditional across the array above using a boolean mask
  filter1 = arr == 5
  filter2 = arr <= 5
  filter3 = arr > 5
  filter4 = arr!= 5
  #print(filter1)
  #print(filter2)
  #print(filter3)
  #print(filter4)

  #use the filters to select only the elements that are true and print the results
  equals_five = arr[filter1]
  print(equals_five)
  less_or_equal_five = arr[filter2]
  print(less_or_equal_five)
  greater_than_five = arr[filter3]
  print(greater_than_five)
  not_equal_five = arr[filter4]
  print(not_equal_five)




filter_an_array()

[5 5]
[4 5 2 1 3 1 2 4 5 3 3 1]
[9 8 8 7 6 7 8 9]
[4 2 9 1 8 3 1 8 2 7 4 3 6 7 3 1 8 9]


### Exercise 8 - How many survivors?

The `Survived` column in the titanic dataset contains two possible values: 0 if the person did not survive and 1 if they did.

Write a function that will:

* create a numpy array from the Survived column of the titanic dataframe `df`
* count the length of the array (*Hint: you can use the `len()` function in the same way as you have done for strings and lists*) to find out how many people were on the titanic
* filter the array for values greater than 0
* find the length of the filtered array and calculate the percentage of survivors, rounded to 1 decimal place
* print a statement that says how many people were on the titanic and what percentage survived.

In [16]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv"
df = pd.read_csv(url)

def get_survival_rate():
  # write your code below to calculate the survival rate of titanic passengers

  #get the colunm "Survived" from the dataframe column
  survived_arr = df['Survived'].to_numpy(np.int16)
  people_count = len(survived_arr) #total number of people on titanic
  print(people_count)

  #create a filter by broadcasting conditional across the array above using a boolean mask
  filter = survived_arr > 0
  survived_people = survived_arr[filter] #use the filters to select only the elements that are true
  survived_count = len(survived_people) #total number of people that survived
  percentage_of_survivors = (survived_count/people_count) * 100 #percentage of people that survived
  percentage_of_survivors = round(percentage_of_survivors, 2) #round percentage of survivor to 2 decimal places
  print(f"{people_count}  was on the titanic and  {percentage_of_survivors} % survived" )







get_survival_rate()

891
891  was on the titanic and  38.38 % survived


### Exercise 9 - Passenger Classes

The `Pclass` column of the titanic dataset `df` shows the class of each passenger aboard, numbered 1 for first class, 2 for second class and 3 for third.

Write a function that will
* create a numpy array from the `Pclass` column
* filters the array for only 1st class passengers and stores the result in a new variable
* prints the number of first class passengers
* repeats steps two and three for second and third class passengers

Expected output:

There were 216 first class passengers <br>
There were 184 second class passengers <br>
There were 491 third class passengers

In [19]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv"
df = pd.read_csv(url)


def get_class_counts():
  # write your code below to calculate the number of passengers in each class

  #get the colunm "Pclass" from the dataframe column
  class_arr = df['Pclass'].to_numpy(np.int8)

  #create a filter if pclass is equals 1 for first class
  filter1 = class_arr == 1
  first_class = class_arr[filter1]  #use the filter to select only the elements that are true
  firstclass_passengers = len(first_class) #get total of first class passengers
  print("There were ", firstclass_passengers,"first class passengers " )

  #create a filter if pclass is equals 2 for second class
  filter2 = class_arr == 2
  second_class = class_arr[filter2] #use the filter to select only the elements that are true
  secondclass_passengers = len(second_class) #get total of second class passengers
  print("There were ", secondclass_passengers,"second class passengers " )

  #create a filter if pclass is equals 3 for second class
  filter3 = class_arr == 3
  third_class = class_arr[filter3] #use the filter to select only the elements that are true
  thirdclass_passengers = len(third_class) #get total of third class passengers
  print("There were ", thirdclass_passengers,"third class passengers " )






get_class_counts()

There were  216 first class passengers 
There were  184 second class passengers 
There were  491 third class passengers 


### Exercise 10 - Survivor Stats

When we have arrays that represent different columns of the same dataset, we can create a boolean mask from one array and then apply it as a filter to a different array.

Write a function that does the following:
* creates separate numpy arrays of the `Pclass` and `Survived` columns of the titanic dataset
* creates a boolean mask to filter those that died (value == 0) using the Survived array
* apply the filter to the Pclass array, assigning it to a new variable
* use filtering in the same way as the previous exercise to find out how many people in each class were aboard the titanic and how many survived
* calculate the percentage of people in each class who survived. Do the results surpise you?

As an extra challenge, if you have completed the worksheet on user-defined functions and are confident with re-using functions, change the `get_class_counts()` function to return a value and use this in your `get_survivor_class_stats()` function.

In [11]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv"
df = pd.read_csv(url)


def get_survivor_class_stats():

  # write your code below to calculate the percentage of survivors in each class
  #get the colunm "Pclass" from the dataframe column
  class_arr = df['Pclass'].to_numpy(np.int8)
  survived_arr = df['Survived'].to_numpy(np.int16)
  filter = survived_arr == 0
  nonsurvivor_in_pclass = class_arr[filter] #use the filters to select only the elements that are true
  nonsurvivor_in_pclass_count = len(nonsurvivor_in_pclass)
  print(nonsurvivor_in_pclass_count)

  #create a filter if pclass is equals 1 for first class
  filter1 = class_arr == 1
  first_class = class_arr[filter1]  #use the filter to select only the elements that are true
  firstclass_passengers = len(first_class)
  print(firstclass_passengers) #get total of first class passengers

  #create a filter if pclass is equals 2 for second class
  filter2 = class_arr == 2
  second_class = class_arr[filter2] #use the filter to select only the elements that are true
  secondclass_passengers = len(second_class) #get total of second class passengers
  print(secondclass_passengers )

  #create a filter if pclass is equals 3 for third class
  filter3 = class_arr == 3
  third_class = class_arr[filter3] #use the filter to select only the elements that are true
  thirdclass_passengers = len(third_class) #get total of third class passengers
  print(thirdclass_passengers)

  #filter for those that survived and in first class
  filter4 = (survived_arr > 0) & (class_arr == 1)
  survivor_firstclass = survived_arr[filter4]
  print(len(survivor_firstclass)) #number of survivor in firstclass
  percentage_survivor_firstclass = ((len(survivor_firstclass)/firstclass_passengers)) * 100 #percentage of survival
  print (f"{firstclass_passengers}  was on first class and  {percentage_survivor_firstclass} % survived" )

  #filter for those that survived and in secondclass
  filter5 = (survived_arr > 0) & (class_arr == 2)
  survivor_secondclass = survived_arr[filter5]
  print(len(survivor_secondclass)) #number of survivor in second class
  percentage_survivor_secondclass = ((len(survivor_secondclass)/secondclass_passengers)) * 100 #percentage of survival
  print (f"{secondclass_passengers}  was on second class and  {percentage_survivor_secondclass} % survived" )

  #filter for those that survived and in third class
  filter6 = (survived_arr > 0) & (class_arr == 3)
  survivor_thirdclass = survived_arr[filter6]
  print(len(survivor_thirdclass)) #number of survivor in third class
  percentage_survivor_thirdclass = ((len(survivor_thirdclass)/thirdclass_passengers)) * 100 #percentage of survival
  print (f"{thirdclass_passengers}  was on third class and  {percentage_survivor_thirdclass} % survived" )

  #sur_firstclass_passenger = first_class[filter2]
  #print(sur_firstclass_passenger)


get_survivor_class_stats()

549
216
184
491
136
216  was on first class and  62.96296296296296 % survived
87
184  was on second class and  47.28260869565217 % survived
119
491  was on third class and  24.236252545824847 % survived


# Reflection
----

## What skills have you demonstrated in completing this notebook?

Your answer: I demonstrated data manipulation skills by effectively using NumPy to create, filter, and transform arrays. Also the ability to extract relevant data subsets using logical conditions and array operations, such as applying element-wise arithmetic and filters like (survived_arr > 0) & (class_arr == 1) to analyze specific groups. Additionally, I efficiently handled tasks like sorting arrays, accessing specific slices (e.g., first and last 5 items), and most importantly the ability to create NumPy arrays from other data structures like lists or pandas columns.

## What caused you the most difficulty?

Exercise 10 was the most challenging for me because it involved filtering data using two conditions. It took longer to figure out the logic, and repeatedly writing similar code for different classes proved to be time-consuming. To improve efficiency, I realize it would be better to use a loop to iterate through the classes and calculate the survival rates. I plan to revisit and optimize this approach at a later time.